name: Build project
on:
    push:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build
